name: Release

on:
  push:
    tags: ["v*.*.*"]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test
      - run: cargo publish -p tribewarez-staking
      - run: cargo publish -p tribewarez-vault
      - run: cargo publish -p tribewarez-swap
      - run: cargo publish -p tribewarez-pot-o
      - uses: softprops/action-gh-release@v2
        if: success()
        with:
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
